In [1]:
import numpy as np

In [7]:
a = np.linspace(0, 3, 15)
a

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [8]:
arr = np.array([[[1.1, 2.1, 3.1],
                 [4.1, 5.1, 6.1]],
                 [[7.1, 8.1, 9.1],
                  [10.1, 11.1, 12.1]]])

In [9]:
arr.dtype

dtype('float64')

In [13]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(2, 2, 3)

In [11]:
arr.size

12

In [12]:
arr.ndim

3

In [19]:
arr2 = arr.reshape(2, 2, 3, 1)
arr2

array([[[[ 1.1],
         [ 2.1],
         [ 3.1]],

        [[ 4.1],
         [ 5.1],
         [ 6.1]]],


       [[[ 7.1],
         [ 8.1],
         [ 9.1]],

        [[10.1],
         [11.1],
         [12.1]]]])

In [20]:
arr2.shape

(2, 2, 3, 1)

In [21]:
arr2.ndim

4

In [23]:
arr3 = arr2.astype(int)
arr3

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

In [26]:
for i in np.nditer(arr3):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [37]:
arr3[1, 0, 1, 0]

8

In [36]:
arr3[0, 1, 1:3, 0]

array([5, 6])

In [38]:
np.where(arr3==8)

(array([1]), array([0]), array([1]), array([0]))

In [42]:
arr4 = arr3.reshape(2, 3, 2)
arr4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [43]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [51]:
arr5 = np.concatenate((arr1, arr2))

In [50]:
np.concatenate((arr1, arr2), axis=1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

In [52]:
np.split(arr5, [1], axis=1)

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'), array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]