In [1]:
import numpy as np

In [7]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
y = np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
x+y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
x.ndim

2

In [10]:
x.shape

(2, 3)

In [13]:
x.size

6

In [14]:
x.dtype

dtype('float64')

In [54]:
w = np.array([[11, 12, 13],
              [14, 15, 16]])
w

array([[11, 12, 13],
       [14, 15, 16]])

In [48]:
z = np.arange(1, 4)
z

array([1, 2, 3])

In [55]:
newArray = np.vstack((z, w))
newArray

array([[ 1,  2,  3],
       [11, 12, 13],
       [14, 15, 16]])

In [56]:
newArray.shape

(3, 3)

In [29]:
for i in newArray:
  print(i)

11
12
13
14
15
16
1
2
3


In [58]:
newArray.T

array([[ 1, 11, 14],
       [ 2, 12, 15],
       [ 3, 13, 16]])

In [64]:
newArray -= 1
newArray

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [65]:
newArray.min()

0

In [66]:
newArray.max()

15

In [67]:
print(newArray[0])

[0 1 2]


In [68]:
print(newArray[newArray==12])

[12]


In [70]:
print(newArray[[0, 2], 0:1])

[[ 0]
 [13]]


In [71]:
newArray.reshape(9,1)

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [72]:
newArray.reshape(3,2)

ValueError: ignored